#!/usr/bin/env python3

import rospy
from geometry_msgs.msg import PoseStamped

def callback(data):
    rospy.loginfo(rospy.get_caller_id() + " تم استلام رسالة من الموضوع burger_pose: %s", data)

def listener():
    rospy.init_node('burger_subscriber', anonymous=True)
    rospy.Subscriber("burger_pose", PoseStamped, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()
